MifosOptions:
  baseUrl: 'https://localhost/fineract-provider/api/v1'
  tenantId: default
  user: root
  pass: Admin123
MessageSender:
  class: TBulkSMSSender
  options:
    uri: 'http://login.tbulksms.com/API/WebSMS/Http/v1.0a/index.php'
    # you TBulkSMS customerid
    userid: 124823
    password: insectyaya91
    format: json
    # your TBulkSMS transactional route id
    route_id: 34
    sender: WEBSMS
